#import "./PassRecordFragment.gql"

mutation passRecord(
  $where: PassRecordWhereUniqueInput!
  $create: PassRecordCreateInput!
  $update: PassRecordUpdateInput!
) {
  passRecord: upsertOnePassRecord(
    where: $where
    create: $create
    update: $update
  ) {
    ...PassRecord
  }
}
