#import "./PassRecordFragment.gql"

query passRecords($limit: Int, $offset: Int, $where: PassRecordWhereInput) {
  passRecords: passRecords(
    first: $limit
    skip: $offset
    where: $where
    orderBy: { date: desc }
  ) {
    ...PassRecord
  }
  # totalCount: passRecord_aggregate (where: $where) {
  #   aggregate {
  #     count
  #   }
  # }
}
