#import "./ResidentFragment.gql"

mutation resident(
  $where: ResidentWhereUniqueInput!
  $create: ResidentCreateInput!
  $update: ResidentUpdateInput!
) {
  resident: upsertOneResident(where: $where, create: $create, update: $update) {
    ...Resident
  }
}
