#import "./ResidentFragment.gql"

query residents($limit: Int, $offset: Int, $where: ResidentWhereInput) {
  residents: residents(first: $limit, skip: $offset, where: $where) {
    ...Resident
  }
  # totalCount: customer_aggregate (where: $where) {
  #   aggregate {
  #     count
  #   }
  # }
}
